name: Generate PDFs

on:
  push:
    branches: [main]
  workflow_dispatch: # Allow manual triggers

jobs:
  generate-pdfs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Astro site
        run: npm run build

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Generate PDFs with Puppeteer
        run: node scripts/generate-pdfs.js

      - name: Upload PDFs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: generated-pdfs
          path: dist/pdfs/
          retention-days: 90

      - name: Deploy PDFs to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/pdfs
          destination_dir: pdfs
          keep_files: true  # Keep existing files
          commit_message: 'Deploy PDFs: ${{ github.sha }}'
